import Link from 'next/link';

export default function PrivacyPolicy() {
  return <main className="container" style={{ padding: '3rem 1rem' }}><article className="card" style={{ maxWidth: 850, margin: '0 auto' }}><p style={{ color: 'var(--primary)', fontWeight: 700 }}>GRACELAND VENUES</p><h1>Privacy Policy</h1><p style={{ color: 'var(--text-muted)' }}>Last updated: 20 August 2026</p>
    <h2>1. Introduction</h2><p>This Privacy Policy explains how Graceland Venues (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) collects, uses, stores, and protects your personal information when you use this website to book tickets, make payments, or otherwise interact with our services.</p><p>We are committed to protecting your privacy in accordance with the Protection of Personal Information Act 4 of 2013 (POPIA).</p><p>Our Information Officer can be contacted at <a href="mailto:conny@gracelandvenues.co.za">conny@gracelandvenues.co.za</a> or +27 72 264 4009.</p>
    <h2>2. Information We Collect</h2><p>We may collect your full name, email address, phone number, booking details, payment information processed by our payment providers, proof-of-payment documents for manual EFT bookings, communications you send us, and basic technical data such as IP address, browser type, and device type.</p><p>We do not knowingly collect sensitive personal information unless it is specifically required for a particular booking type, in which case we will ask for explicit consent.</p>
    <h2>3. How We Use Your Information</h2><ul><li>Process and confirm your booking.</li><li>Generate and deliver QR-code entry tickets.</li><li>Verify payments and proof-of-payment uploads.</li><li>Communicate booking confirmations, changes, or closures.</li><li>Respond to support queries and improve our services.</li><li>Comply with legal and tax record-keeping obligations.</li></ul><p>We do not sell your personal information.</p>
    <h2>4. Sharing Your Information</h2><p>Necessary information may be shared with operators who help us provide the service:</p><ul><li>PayFast and Yoco for payment processing. We do not store your full card details.</li><li>Supabase for securely storing booking records and proof-of-payment uploads.</li><li>Resend for delivering booking confirmations and QR tickets.</li></ul><p>We only share what is necessary for these providers to perform their functions. We may disclose information where required by law or to protect our legal rights.</p>
    <h2>5. Data Retention</h2><p>We retain booking and payment records for as long as necessary and thereafter as required by South African tax and financial record-keeping laws. Proof-of-payment files are retained for the same audit purposes.</p>
    <h2>6. Data Security</h2><p>We use HTTPS/SSL, access controls, secure non-public storage for proof uploads, and regular security reviews. No internet transmission or storage system is completely secure.</p>
    <h2>7. Your Rights</h2><p>Under POPIA, you may request access to, correction or deletion of your personal information, subject to legal retention obligations; object to direct marketing; and lodge a complaint with the Information Regulator of South Africa. Contact <a href="mailto:conny@gracelandvenues.co.za">conny@gracelandvenues.co.za</a> to exercise these rights.</p>
    <h2>8. Cookies</h2><p>We may use essential cookies required for the booking process. We do not use third-party advertising or tracking cookies without consent.</p>
    <h2>9. Children&apos;s Information</h2><p>Our services are intended for adults booking for themselves, their families, or groups. Bookings involving minors must be made and consented to by a parent or legal guardian.</p>
    <h2>10. Changes</h2><p>We may update this policy from time to time. The date above will reflect the latest revision.</p>
    <h2>11. Contact Us</h2><p>Graceland Venues<br /><a href="mailto:conny@gracelandvenues.co.za">conny@gracelandvenues.co.za</a><br />072 264 4009</p><Link className="btn" href="/">Back to booking</Link>
  </article></main>;
}
