'use client';

import { useEffect, useState } from 'react';
import { supabaseBrowser } from '@/lib/supabase-browser';

type Sales = { units: number; revenue: number };
type Overview = { date: string; today: { headcount: number; revenue: number; bookings: number; unscanned: number; scanned: number; capacity: number; breakdown: Record<string, Sales> }; comparison: { lastWeekHeadcount: number; percent: number | null }; pendingProofs: number };

export default function AdminDashboard() {
  const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState(''); const [selectedDate, setSelectedDate] = useState(() => new Date().toISOString().slice(0, 10)); const [loading, setLoading] = useState(true); const [chartMode, setChartMode] = useState<'units' | 'revenue'>('units');
  const [conflictCount, setConflictCount] = useState(0);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Initial data fetch on mount; setState is asynchronous
  useEffect(() => { let active = true; setLoading(true); setError(''); supabaseBrowser.auth.getSession().then(({ data: sessionData }) => { if (!sessionData.session) throw new Error('Staff session has expired'); const token = sessionData.session.access_token; const headers = { Authorization: `Bearer ${token}` }; Promise.all([ fetch(`/api/admin/overview?date=${selectedDate}`, { headers, cache: 'no-store' }), fetch(`/api/admin/conflicts?date=${selectedDate}`, { headers, cache: 'no-store' }).catch(() => null), ]).then(async ([overviewRes, conflictsRes]) => { const body = await overviewRes.json(); if (!overviewRes.ok) throw new Error(body.error); if (active) setData(body); if (conflictsRes && conflictsRes.ok) { const cData = await conflictsRes.json(); if (active) setConflictCount(cData.count || 0); } }); }).catch(err => { if (active) setError(err instanceof Error ? err.message : 'Could not load dashboard'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [selectedDate]);
  const changeDate = (days: number) => setSelectedDate(current => { const [year, month, day] = current.split('-').map(Number); return new Date(Date.UTC(year, month - 1, day + days)).toISOString().slice(0, 10); });
  const exportCsv = async () => { const session = (await supabaseBrowser.auth.getSession()).data.session; if (!session) return; const response = await fetch(`/api/admin/export?date=${selectedDate}`, { headers: { Authorization: `Bearer ${session.access_token}` } }); if (!response.ok) { setError('Could not export bookings'); return; } const blob = await response.blob(); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `graceland-bookings-${selectedDate}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  if (error && !data) return <main className="container" style={{ padding: '2rem 1rem' }}><div className="card" style={{ color: 'var(--danger)' }}>{error}</div></main>;
  if (!data) return <main className="container" style={{ padding: '2rem 1rem' }}><div className="card">Loading dashboard…</div></main>;
  const percent = Math.min(100, Math.round((data.today.headcount / data.today.capacity) * 100)); const comparison = data.comparison.percent === null ? 'No comparison data' : `${data.comparison.percent >= 0 ? '+' : ''}${data.comparison.percent.toFixed(1)}% vs last week`; const sales = Object.entries(data.today.breakdown); const max = Math.max(1, ...sales.map(([, value]) => chartMode === 'units' ? value.units : value.revenue));
  return <main className="container" style={{ padding: '2rem 1rem' }}>
    <div className="admin-header">
      <div><p style={{ color: 'var(--primary)', fontWeight: 700 }}>STAFF OPERATIONS</p><h1>Daily overview</h1></div>
      <nav className="admin-nav"><a className="btn" href="/admin/proofs" style={{ border: '1px solid var(--border-color)' }}>Proof reviews</a><a className="btn" href="/admin/bookings" style={{ border: '1px solid var(--border-color)' }}>View all bookings</a><a className="btn" href="/admin/reports" style={{ border: '1px solid var(--border-color)' }}>Reports</a><a className="btn" href="/admin/settings" style={{ border: '1px solid var(--border-color)' }}>Prices &amp; dates</a><a className="btn" href="/admin/audit" style={{ border: '1px solid var(--border-color)' }}>Audit log</a><button className="btn" onClick={exportCsv} style={{ border: '1px solid var(--border-color)' }}>Export CSV</button><a className="btn btn-primary" href="/admin/scanner">Open scanner</a></nav>
    </div>
    <div className="card" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.75rem', flexWrap: 'wrap', marginBottom: '1rem' }}>
      <button type="button" className="btn" aria-label="Previous day" onClick={() => changeDate(-1)} style={{ border: '1px solid var(--border-color)', fontSize: '1.25rem' }}>←</button>
      <input type="date" value={selectedDate} onChange={event => setSelectedDate(event.target.value)} style={{ padding: '0.7rem', border: '1px solid var(--border-color)', borderRadius: 8, fontWeight: 700, maxWidth: 180 }} />
      <span style={{ minWidth: 140, textAlign: 'center', fontWeight: 700, fontSize: '0.9rem' }}>{new Date(`${selectedDate}T00:00:00`).toLocaleDateString(undefined, { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' })}{loading && <span style={{ display: 'block', color: 'var(--text-muted)', fontSize: '0.8rem' }}>Updating…</span>}</span>
      <button type="button" className="btn" aria-label="Next day" onClick={() => changeDate(1)} style={{ border: '1px solid var(--border-color)', fontSize: '1.25rem' }}>→</button>
    </div>
    {error && <div className="card" style={{ marginBottom: '1rem', color: 'var(--danger)' }}>{error}</div>}
    <div className="admin-stats">
      <div className="card"><p style={{ color: 'var(--text-muted)' }}>Booked headcount</p><strong style={{ fontSize: '2.5rem', color: 'var(--primary)' }}>{data.today.headcount}</strong><p style={{ color: 'var(--text-muted)' }}>{comparison}</p></div>
      <div className="card"><p style={{ color: 'var(--text-muted)' }}>Revenue</p><strong style={{ fontSize: '2.5rem', color: 'var(--success)' }}>R {data.today.revenue.toFixed(2)}</strong><p>{data.today.bookings} bookings</p></div>
      <div className="card"><p style={{ color: 'var(--text-muted)' }}>Pending EFT proofs</p><strong style={{ fontSize: '2.5rem', color: 'var(--warning)' }}>{data.pendingProofs}</strong><p><a href="/admin/proofs" style={{ color: 'var(--primary)' }}>Review queue →</a></p></div>
      <div className="card"><p style={{ color: 'var(--text-muted)' }}>Scanned</p><strong style={{ fontSize: '2.5rem' }}>{data.today.scanned}</strong><p>{data.today.unscanned} valid tickets remaining</p></div>
      {conflictCount > 0 && <a href="/admin/conflicts" className="card" style={{ borderLeft: '4px solid var(--danger)', textDecoration: 'none', display: 'block' }}><p style={{ color: 'var(--danger)', fontWeight: 700 }}>⚠ Duplicate Check-ins</p><strong style={{ fontSize: '2.5rem', color: 'var(--danger)' }}>{conflictCount}</strong><p><span style={{ color: 'var(--primary)' }}>Review alerts →</span></p></a>}
    </div>
    <div className="card" style={{ marginBottom: '1rem' }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2>Capacity</h2><strong>{percent}%</strong></div><div style={{ height: 14, background: '#e2e8f0', borderRadius: 20, marginTop: 12 }}><div style={{ height: '100%', width: `${percent}%`, background: percent >= 90 ? 'var(--danger)' : percent >= 70 ? 'var(--warning)' : 'var(--success)', borderRadius: 20 }} /></div><p style={{ color: 'var(--text-muted)', marginTop: 8 }}>{data.today.headcount} of {data.today.capacity} booked places</p></div>
    <div className="card"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginBottom: '1rem' }}><h2>Sales by pass type</h2><div><button className="btn" onClick={() => setChartMode('units')} style={{ border: '1px solid var(--border-color)', background: chartMode === 'units' ? '#e0f2fe' : 'transparent' }}>Units</button><button className="btn" onClick={() => setChartMode('revenue')} style={{ border: '1px solid var(--border-color)', marginLeft: 6, background: chartMode === 'revenue' ? '#e0f2fe' : 'transparent' }}>Revenue</button></div></div>{sales.length === 0 ? <p style={{ color: 'var(--text-muted)' }}>No paid sales for this date.</p> : sales.map(([name, value]) => { const amount = chartMode === 'units' ? value.units : value.revenue; return <div key={name} style={{ marginBottom: '0.8rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8 }}><span style={{ wordBreak: 'break-word' }}>{name}</span><strong style={{ whiteSpace: 'nowrap' }}>{chartMode === 'units' ? value.units : `R ${value.revenue.toFixed(2)}`}</strong></div><div style={{ height: 12, background: '#e2e8f0', borderRadius: 10, marginTop: 5 }}><div style={{ width: `${Math.round((amount / max) * 100)}%`, height: '100%', background: 'var(--primary)', borderRadius: 10 }} /></div></div>; })}</div>
  </main>;
}
