'use client';

import { useEffect, useState } from 'react';
import { supabaseBrowser } from '@/lib/supabase-browser';

type Customer = { first_name: string; last_name: string; email: string; phone: string };
type Booking = { id: string; reference: string; visit_date: string; status: string; payment_method: string | null; total_amount: number; people_count: number; created_at: string; refunded_at?: string | null; voucher_issued?: boolean; customers?: Customer | Customer[]; booking_items?: Array<{ quantity: number; subtotal: number; metadata: { name?: string } | null; packages?: Array<{ name: string }>; huts?: Array<{ name: string }> }>; tickets?: Array<{ id: string; ticket_uid: string; status: string }> };
type Action = 'resend_tickets' | 'delete' | 'mark_paid' | 'refund' | 'cancel_ticket';
const customerOf = (booking: Booking) => Array.isArray(booking.customers) ? booking.customers[0] : booking.customers;

export default function BookingsAdmin() {
  const [query, setQuery] = useState(''); const [bookings, setBookings] = useState<Booking[]>([]); const [selected, setSelected] = useState<Booking | null>(null); const [message, setMessage] = useState('Loading bookings...'); const [toast, setToast] = useState(''); const [busy, setBusy] = useState(''); const [refundDate, setRefundDate] = useState(new Date().toISOString().slice(0, 10));
  const token = async () => (await supabaseBrowser.auth.getSession()).data.session?.access_token || '';
  const load = async (search = query) => { const response = await fetch(`/api/admin/bookings?q=${encodeURIComponent(search)}`, { headers: { Authorization: `Bearer ${await token()}` }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setBookings(data.bookings); setSelected(current => current ? data.bookings.find((booking: Booking) => booking.id === current.id) || null : null); setMessage(data.bookings.length ? '' : 'No bookings found.'); };
  useEffect(() => { load().catch(error => setMessage(error.message)); }, []);
  const showToast = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 6000); };
  const action = async (type: Action, ticketId?: string) => {
    if (!selected || busy) return;
    if (type === 'delete' && !window.confirm(`Permanently delete booking ${selected.reference}?`)) return;
    if (type === 'refund' && !window.confirm(`Cancel ${selected.reference} and issue a voucher for R ${Number(selected.total_amount).toFixed(2)}? All valid tickets will be invalidated.`)) return;
    if (type === 'mark_paid' && !window.confirm(`Mark booking ${selected.reference} as paid and issue tickets?`)) return;
    setBusy(type); setMessage(type === 'refund' ? 'Issuing voucher refund... please wait.' : 'Processing booking action... please wait.');
    try {
      const endpoint = type === 'refund' ? `/api/admin/bookings/${selected.id}/refund` : '/api/admin/bookings';
      const response = await fetch(endpoint, { method: 'POST', headers: { Authorization: `Bearer ${await token()}`, 'Content-Type': 'application/json' }, body: type === 'refund' ? undefined : JSON.stringify({ bookingId: selected.id, action: type, ticketId, reason: window.prompt('Reason (optional):') || null }) });
      const data = await response.json(); setMessage(data.message || data.error); if (!response.ok) return;
      if (type === 'delete') setSelected(null); await load();
      if (type === 'resend_tickets') showToast('Tickets resent successfully');
      if (type === 'refund') showToast(data.emailSent ? 'Voucher issued and email sent' : 'Voucher issued; email queued for retry');
    } finally { setBusy(''); }
  };
  const refundAll = async () => { if (busy) return; const eligible = bookings.filter(booking => booking.visit_date === refundDate && ['PAID', 'CONFIRMED'].includes(booking.status) && !booking.voucher_issued); const total = eligible.reduce((sum, booking) => sum + Number(booking.total_amount), 0); if (!eligible.length) return setMessage('No paid, unrefunded bookings found for that date.'); if (!window.confirm(`Issue vouchers for ${eligible.length} bookings on ${refundDate}, totalling R ${total.toFixed(2)}? This will cancel them and invalidate their tickets.`)) return; setBusy('refund-all'); setMessage('Issuing vouchers for the selected date... please wait.'); try { const response = await fetch('/api/admin/bookings/refund-all', { method: 'POST', headers: { Authorization: `Bearer ${await token()}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ date: refundDate }) }); const data = await response.json(); setMessage(data.message || data.error); if (response.ok) { showToast(data.message); await load(); } } finally { setBusy(''); } };
  return <main className="container" style={{ padding: '2rem 1rem' }}>{toast && <div role="status" style={{ position: 'fixed', top: 24, right: 24, zIndex: 20, background: '#065f46', color: 'white', padding: '1rem 1.25rem', borderRadius: 10 }}>✓ {toast}</div>}<div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem', flexWrap: 'wrap', marginBottom: '1.5rem' }}><div><p style={{ color: 'var(--primary)', fontWeight: 700 }}>OPERATIONS</p><h1>All bookings</h1></div><div style={{ display: 'flex', gap: 8 }}><a className="btn" href="/admin/vouchers">Vouchers</a><a className="btn" href="/admin">Dashboard</a></div></div><div className="card" style={{ marginBottom: '1rem' }}><form onSubmit={event => { event.preventDefault(); load().catch(error => setMessage(error.message)); }} style={{ display: 'flex', gap: 8 }}><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search booking ref, ticket ID, name, or email" style={{ flex: 1, padding: '0.8rem', border: '1px solid var(--border-color)', borderRadius: 8 }} /><button className="btn btn-primary">Search</button></form><div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap', marginTop: 12 }}><label>Refund all paid bookings for <input type="date" value={refundDate} onChange={event => setRefundDate(event.target.value)} style={{ padding: 8, marginLeft: 4 }} /></label><button className="btn" onClick={refundAll} style={{ color: '#b91c1c', border: '1px solid #b91c1c' }}>Refund all for date</button></div></div>{message && <p style={{ color: 'var(--text-muted)', marginBottom: '1rem' }}>{message}</p>}<div style={{ display: 'grid', gridTemplateColumns: selected ? 'minmax(280px, 0.8fr) minmax(320px, 1.2fr)' : '1fr', gap: '1rem' }}><div style={{ display: 'grid', gap: '0.75rem', alignContent: 'start' }}>{bookings.map(booking => { const customer = customerOf(booking); return <button key={booking.id} onClick={() => setSelected(booking)} style={{ textAlign: 'left', background: selected?.id === booking.id ? '#e0f2fe' : 'white', border: '1px solid var(--border-color)', borderRadius: 10, padding: '1rem' }}><strong style={{ color: 'var(--primary)' }}>{booking.reference}</strong><p>{customer?.first_name} {customer?.last_name}</p><p style={{ color: 'var(--text-muted)' }}>{booking.visit_date} · R {Number(booking.total_amount).toFixed(2)} · {booking.voucher_issued ? 'Voucher issued' : booking.status}</p></button>; })}</div>{selected && <BookingDetail booking={selected} onAction={action} />}</div></main>;
}

function BookingDetail({ booking, onAction }: { booking: Booking; onAction: (action: Action, ticketId?: string) => void }) { const customer = customerOf(booking); return <section className="card"><div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, flexWrap: 'wrap' }}><div><p style={{ color: 'var(--primary)', fontWeight: 700 }}>{booking.reference}</p><h2>Booking details</h2></div><span style={{ padding: '0.35rem 0.65rem', borderRadius: 20, background: booking.voucher_issued ? '#dbeafe' : booking.status === 'PAID' ? '#dcfce7' : '#fef3c7' }}>{booking.voucher_issued ? 'Voucher issued' : booking.status}</span></div><div style={{ marginTop: '1rem', display: 'grid', gap: '0.5rem' }}><p><strong>Customer:</strong> {customer?.first_name} {customer?.last_name}</p><p><strong>Email:</strong> {customer?.email}</p><p><strong>Phone:</strong> {customer?.phone}</p><p><strong>Visit date:</strong> {booking.visit_date}</p><p><strong>Total:</strong> R {Number(booking.total_amount).toFixed(2)}</p><p><strong>People:</strong> {booking.people_count}</p><p><strong>Payment:</strong> {booking.payment_method || 'Pending'}</p>{booking.refunded_at && <p><strong>Voucher issued:</strong> {new Date(booking.refunded_at).toLocaleString()}</p>}</div><h3 style={{ marginTop: '1.5rem' }}>Items</h3>{booking.booking_items?.map((item, index) => <p key={index} style={{ borderBottom: '1px solid var(--border-color)', padding: '0.5rem 0' }}>{item.packages?.[0]?.name || item.huts?.[0]?.name || item.metadata?.name || 'Booking item'} × {item.quantity} · R {Number(item.subtotal).toFixed(2)}</p>)}<h3 style={{ marginTop: '1.5rem' }}>Tickets</h3>{booking.tickets?.length ? booking.tickets.map(ticket => <div key={ticket.id} style={{ display: 'flex', justifyContent: 'space-between', gap: 8, borderBottom: '1px solid var(--border-color)', padding: '0.5rem 0' }}><span>{ticket.ticket_uid} · <strong>{ticket.status}</strong></span>{ticket.status === 'VALID' && <button className="btn" style={{ color: 'var(--danger)', border: '1px solid var(--danger)', padding: '0.35rem 0.6rem' }} onClick={() => onAction('cancel_ticket', ticket.id)}>Invalidate</button>}</div>) : <p style={{ color: 'var(--text-muted)' }}>No tickets issued.</p>}<div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: '1.5rem' }}><button className="btn btn-primary" onClick={() => onAction('resend_tickets')}>Resend tickets</button><button className="btn" onClick={() => onAction('mark_paid')}>Mark as paid & issue tickets</button>{!booking.voucher_issued && <button className="btn" style={{ color: '#b91c1c', border: '1px solid #b91c1c' }} onClick={() => onAction('refund')}>Issue voucher refund</button>}<button className="btn" style={{ color: 'var(--danger)', border: '1px solid var(--danger)' }} onClick={() => onAction('delete')}>Delete booking</button></div></section>; }
